### ISSUE TITLE
Unexpected Behavior with Generic Parameters

### ISSUE THREAD

**Issue by danechambers** [autofac/Autofac.Extras.AggregateService#11] opened 2022-01-11 09:36 UTC
I'm not sure if this is working as designed or not, but it is something that caught me off guard. Please feel free to correct any misconceptions I may have about how the library should work.

## Describe the Bug
When a method on the aggregate services interface accepts a generic parameter, a new instance of the parameter is created (or is attempted to) when invoking the method rather than using the parameter that is given to it.

## Steps to Reproduce
I added a new pass-through interface and implementation
```c#
    public interface IPassThroughOpenGeneric<T>
    {
        IOpenGeneric<T> OpenGeneric { get; }
    }

    public class OpenGenericPassThroughImpl<T> : IPassThroughOpenGeneric<T>
    {
        public OpenGenericPassThroughImpl(IOpenGeneric<T> openGeneric)
        {
            OpenGeneric = openGeneric;
        }

        public IOpenGeneric<T> OpenGeneric { get; }
    }
````
and added this method to `IOpenGenericAggregate`
```c#
        IPassThroughOpenGeneric<T> PassThroughOpenGeneric<T>(IOpenGeneric<T> openGeneric);
```

In `AggregateServiceGenericsFixture`, I added this registration
```c#
    builder.RegisterGeneric(typeof(OpenGenericPassThroughImpl<>))
        .As(typeof(IPassThroughOpenGeneric<>));
```
then this test
```c#
        [Fact]
        public void Method_UnpackOpenGeneric()
        {
            var aggregateService = _container.Resolve<IOpenGenericAggregate>();

            var generic = aggregateService.GetOpenGeneric<It.IsAnyType>();

// -----works as expected-----
            var passThroughFunc = _container.Resolve<Func<IOpenGeneric<It.IsAnyType>, IPassThroughOpenGeneric<It.IsAnyType>>>();
            var genericFromPassThroughFunc = passThroughFunc(generic);
//----------
            Assert.Same(generic, genericFromPassThroughFunc.OpenGeneric);
        }
```
However, if I use the aggregate service instead, it does not work.
```c#
        [Fact]
        public void Method_UnpackOpenGeneric()
        {
            var aggregateService = _container.Resolve<IOpenGenericAggregate>();

            var generic = aggregateService.GetOpenGeneric<It.IsAnyType>();

// -----does not work-----
            var genericPassThrough = aggregateService.PassThroughOpenGeneric(generic);
//----------
            Assert.Same(generic, genericPassThrough.OpenGeneric);
        }
```

## Expected Behavior
I am under the impression that the aggregate service should behave as the `Func<>` does. Here is my example if you like to see my full implementation:
[GenericParameterExample.zip](https://github.com/autofac/Autofac.Extras.AggregateService/files/7845345/GenericParameterExample.zip)

## Dependency Versions

Autofac: v6.0.0

**Comment by tillig** [comment] 2022-01-11 13:49
It would be helpful to have all the relevant code (eg, `IOpenGenericAggregate` and the code to build the container) posted if possible. I recognize the zip file is there, but that's sort of hard to work with on, say, a mobile device. Posting the code visibly can help you get an answer faster.

**Comment by danechambers** [comment] 2022-01-11 16:42
I have pushed my changes here: https://github.com/danechambers/Autofac.Extras.AggregateService/tree/v6.1.1-branch
- [IOpenGenericAggregate](https://github.com/danechambers/Autofac.Extras.AggregateService/blob/v6.1.1-branch/test/Autofac.Extras.AggregateService.Test/IOpenGenericAggregate.cs)
- [IPassThroughOpenGeneric](https://github.com/danechambers/Autofac.Extras.AggregateService/blob/v6.1.1-branch/test/Autofac.Extras.AggregateService.Test/IPassThroughOpenGeneric.cs)
- [OpenGenericPassThroughImpl](https://github.com/danechambers/Autofac.Extras.AggregateService/blob/v6.1.1-branch/test/Autofac.Extras.AggregateService.Test/OpenGenericPassThroughImpl%7BT%7D.cs)
- [AggregateServiceGenericsFixture](https://github.com/danechambers/Autofac.Extras.AggregateService/blob/v6.1.1-branch/test/Autofac.Extras.AggregateService.Test/AggregateServiceGenericsFixture.cs)

Hope this helps! Let me know if you need more information.

**Comment by tillig** [comment] 2022-01-11 16:56
Oh, man, I'm sorry I probably wasn't speaking clearly. When I said "having it posted" I meant "right here in the issue" so when folks come in and read this...

> and added this method to `IOpenGenericAggregate`

...the code for `IOpenGenericAggregate` is actually _right here in the issue_, fully self-contained. I apologize for being sorta pedantic on this. I realize it's probably painful. There's method to the madness!

- I (personally) have limited time to address all the questions and, honestly, there's a touch of OSS maintainer burnout, so I get to answering most questions on my phone while I'm watching TV or [sorta?] spending time with the family.
- Seeing all the code in one spot, when that's possible, can sometimes make it clear what's going on without having to dive into debugging territory.
- Later when we close this issue out, we will still have all the code right here in the issue so if folks are searching for it or if we want to know why we made a decision, it's right there, searchable/indexed and all spelled out. Remote repos work while we're fixing it, but they mysteriously disappear after the issue gets resolved; zip files are great but not indexed for search and hard to work with in mobile.

It may be that one of the other maintainers might be able to dive in more interactively. It might be a day or three before I can look at it. I was just hoping to potentially see something obvious without going spelunking.

**Comment by danechambers** [comment] 2022-01-11 17:06
That makes complete sense. I totally get the burnout too. Thank you for the context, I really do appreciate your time. 
If you think this is something worth looking into, I can help dive into the issue too. 🙂

I've posted the code for `IOpenGenericAggregate` below.

```c#
namespace Autofac.Extras.AggregateService.Test
{
    public interface IOpenGenericAggregate
    {
        IOpenGeneric<T> GetOpenGeneric<T>();

        IOpenGeneric<string> GetResolvedGeneric();

        IPassThroughOpenGeneric<T> PassThroughOpenGeneric<T>(IOpenGeneric<T> openGeneric);
    }
}
```
Here is the full fixture as well
```c#
namespace Autofac.Extras.AggregateService.Test
{
    public class AggregateServiceGenericsFixture
    {
        private readonly IContainer _container;

        public AggregateServiceGenericsFixture()
        {
            var builder = new ContainerBuilder();
            builder.RegisterAggregateService<IOpenGenericAggregate>();
            builder.RegisterGeneric(typeof(OpenGenericImpl<>))
                .As(typeof(IOpenGeneric<>));
            builder.RegisterGeneric(typeof(OpenGenericPassThroughImpl<>))
                .As(typeof(IPassThroughOpenGeneric<>));

            _container = builder.Build();
        }

        /// <summary>
        /// Attempts to resolve an open generic by a method call.
        /// </summary>
        [Fact]
        public void Method_ResolveOpenGeneric()
        {
            var aggregateService = _container.Resolve<IOpenGenericAggregate>();

            var generic = aggregateService.GetOpenGeneric<object>();
            Assert.NotNull(generic);

            var ungeneric = aggregateService.GetResolvedGeneric();
            Assert.NotNull(ungeneric);
            Assert.NotSame(generic, ungeneric);
        }

        [Fact]
        public void Method_UnpackOpenGeneric()
        {
            var aggregateService = _container.Resolve<IOpenGenericAggregate>();

            var generic = aggregateService.GetOpenGeneric<It.IsAnyType>();

            // works
            var passThroughFunc = _container.Resolve<Func<IOpenGeneric<It.IsAnyType>, IPassThroughOpenGeneric<It.IsAnyType>>>();
            var genericFromPassThroughFunc = passThroughFunc(generic);
            Assert.Same(generic, genericFromPassThroughFunc.OpenGeneric);

            // doesn't work
            var genericPassThrough = aggregateService.PassThroughOpenGeneric(generic);
            Assert.Same(generic, genericPassThrough.OpenGeneric);
        }
    }
}
```
Anything else I can do, please let me know.

**Comment by tillig** [comment] 2022-01-11 18:03
That helps, thanks!

Things I'm thinking about as I see it now (just brainstorming)...

`It.IsAnyType` is a Moq thing. Moq uses Castle.DynamicProxy under the covers just like AggregateService does for its stuff. I don't know what's underlying `It.IsAnyType` - does this test fail if you use a real type and not a Moq placeholder?

If you make a closed generic version of `IOpenGeneric<T>`, like `public class ClosedGeneric : IOpenGeneric<string>` and use that as the parameter value for the `PassThroughOpenGeneric<T>(xxx)` method, does it work? Probably not, but curious if it makes a difference.

If something is amiss, it's probably going to be [in this bit where the dynamic proxy is building up the list of methods](https://github.com/autofac/Autofac.Extras.AggregateService/blob/870c783f71e3f0634e57f64aaec2b7bdc44cea96/src/Autofac.Extras.AggregateService/ResolvingInterceptor.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L117) and figuring out the backing implementations. I don't see that we have unit tests that cover methods that take generics as parameters so that's likely where I'd start looking.

**Comment by tillig** [comment] 2022-01-14 20:37
[The problem is here](https://github.com/autofac/Autofac.Extras.AggregateService/blob/870c783f71e3f0634e57f64aaec2b7bdc44cea96/src/Autofac.Extras.AggregateService/ResolvingInterceptor.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L123), where the method handler basically says, "Add a parameter of type `IOpenGeneric<T>` to the list, with the value of this closed generic `IOpenGeneric<SomeType>`. Autofac looks for a typed parameter with the type `IOpenGeneric<SomeType>`, doesn't see it, and skips on past.

The existing mechanism is simple and it works, but it's not as rich as the [full-on `Func<X, Y>` factory generator in core Autofac](https://github.com/autofac/Autofac/blob/develop/src/Autofac/Features/GeneratedFactories/FactoryGenerator.cs).

I'm not sure what the best route to fixing this is.

My gut says [the most robust solution would be to do something similar to what the `GeneratedFactoryRegistrationSource` does](https://github.com/autofac/Autofac/blob/be2a437ca048a7534a5ed7936334d1336291aa1d/src/Autofac/Features/GeneratedFactories/GeneratedFactoryRegistrationSource.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L48) and use the factory generator to build the `Func<X, Y>` that underlies the method. The downside is that, with an open generic, it could be expensive because you'll have to do that for every call, unless you also introduce a caching mechanism to store every combination of `IOpenGeneric<T>` to generated factory (which core Autofac does for generated factories when it caches registrations for things). But that would be the most robust, and it'd support all the stuff core Autofac `Func<X, Y>` does.

Possibly simpler but _looking_ more complicated, would be to build the delegate `Func<X, Y>` through reflection and then resolve that function and execute it. Which is to say, build up the type `Func<IOpenGeneric<T>, IPassThroughGeneric<T>>` and resolve that, then execute that factory with the parameters provided. It would mean less complexity tying to the factory generator and it should technically still support all the core Autofac features.

I'll see if I can get that second idea working.

**Closed as completed** 2022-01-15 17:30 UTC

**Comment by tillig** [comment] 2022-01-15 17:33
I won't have time until next week to cut a release with the fix, but it'll happen.

**Comment by danechambers** [comment] 2022-01-18 04:01
Thank you again for your time on this. I definitely appreciate this project (in addition to autofac core) and all the time/effort that everybody puts into it. Looking forward to the release 🙂.

**Comment by tillig** [comment] 2022-01-18 15:16
v6.1.2 published.
